model_list:
  - model_name: qwen3-coder
    litellm_params:
      model: ollama/qwen3-coder
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: ollama/qwen3-coder
  - model_name: gpt-4
    litellm_params:
      model: ollama/qwen3-coder

general_settings:
  master_key: "YOUR_API_KEY_HERE"
  drop_params: true
  debug_level: "DEBUG"