version: '3.8'
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ./ollama-data:/root/.ollama
      - ./models:/home/ollama/models
    ports:
      - "11434:11434"
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_ORIGINS=*

  litellm:
    image: litellm/litellm:latest
    container_name: litellm-proxy
    ports:
      - "8000:8000"
    volumes:
      - ./configs/litellm-config.yaml:/app/config.yaml
    command: "--config /app/config.yaml --host 0.0.0.0 --port 8000"
    depends_on:
      - ollama
    restart: unless-stopped